; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 5
; RUN: opt < %s -passes=instrumentor -instrumentor-read-config-file=%S/default_config.json -S | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"

@A1 = dso_local global i32 0, align 4
@A2 = dso_local constant i32 0, align 4
@A3 = internal global i32 0, align 4
@A4 = internal constant i32 0, align 4
@A5 = external global i32, align 4
@A6 = external constant i32, align 4
@B1 = dso_local global ptr null, align 8
@B2 = dso_local constant ptr null, align 8
@B3 = internal global ptr null, align 8
@B4 = internal constant ptr null, align 8
@B5 = external global ptr, align 8
@B6 = external constant ptr, align 8
@C1 = dso_local global [100 x i32] zeroinitializer, align 16
@C2 = dso_local constant [100 x i32] zeroinitializer, align 16
@C3 = internal global [100 x i32] zeroinitializer, align 16
@C4 = internal constant [100 x i32] zeroinitializer, align 16
@C5 = external global [100 x i32], align 16
@C6 = external constant [100 x i32], align 16
@D1 = dso_local global x86_fp80 0xK00000000000000000000, align 16
@D2 = dso_local constant x86_fp80 0xK00000000000000000000, align 16
@D3 = internal global x86_fp80 0xK00000000000000000000, align 16
@D4 = internal constant x86_fp80 0xK00000000000000000000, align 16
@D5 = external global x86_fp80, align 16
@D6 = external global x86_fp80, align 16

!llvm.module.flags = !{!0, !1, !2, !3, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{i32 7, !"frame-pointer", i32 2}
!5 = !{!"clang version 21.0.0git (https://github.com/jdoerfert/llvm-project.git 1ccefa476b21fceb24068bd85db34b822c51f606)"}
; CHECK-LABEL: define private void @__instrumentor_ctor() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = alloca x86_fp80, align 16
; CHECK-NEXT:    [[TMP1:%.*]] = alloca [100 x i32], align 4
; CHECK-NEXT:    call void @__instrumentor_pre_module(ptr @__instrumentor_.str, ptr @__instrumentor_.str.1) #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    [[TMP2:%.*]] = call ptr @__instrumentor_pre_globals(ptr @A1, ptr @__instrumentor_.str.2, i64 0, i32 4, i8 0) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP2]], ptr @__instrumentor_shadow.A1, align 8
; CHECK-NEXT:    [[TMP3:%.*]] = call ptr @__instrumentor_pre_globals(ptr @A2, ptr @__instrumentor_.str.3, i64 0, i32 4, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP3]], ptr @__instrumentor_shadow.A2, align 8
; CHECK-NEXT:    [[TMP4:%.*]] = call ptr @__instrumentor_pre_globals(ptr @A3, ptr @__instrumentor_.str.4, i64 0, i32 4, i8 0) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP4]], ptr @__instrumentor_shadow.A3, align 8
; CHECK-NEXT:    [[TMP5:%.*]] = call ptr @__instrumentor_pre_globals(ptr @A4, ptr @__instrumentor_.str.5, i64 0, i32 4, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP5]], ptr @__instrumentor_shadow.A4, align 8
; CHECK-NEXT:    [[TMP6:%.*]] = call ptr @__instrumentor_pre_globals(ptr @A5, ptr @__instrumentor_.str.6, i64 0, i32 0, i8 0) #[[ATTR0]]
; CHECK-NEXT:    [[TMP7:%.*]] = call ptr @__instrumentor_pre_globals(ptr @A6, ptr @__instrumentor_.str.7, i64 0, i32 0, i8 1) #[[ATTR0]]
; CHECK-NEXT:    [[TMP8:%.*]] = call ptr @__instrumentor_pre_globals(ptr @B1, ptr @__instrumentor_.str.8, i64 0, i32 8, i8 0) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP8]], ptr @__instrumentor_shadow.B1, align 8
; CHECK-NEXT:    [[TMP9:%.*]] = call ptr @__instrumentor_pre_globals(ptr @B2, ptr @__instrumentor_.str.9, i64 0, i32 8, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP9]], ptr @__instrumentor_shadow.B2, align 8
; CHECK-NEXT:    [[TMP10:%.*]] = call ptr @__instrumentor_pre_globals(ptr @B3, ptr @__instrumentor_.str.10, i64 0, i32 8, i8 0) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP10]], ptr @__instrumentor_shadow.B3, align 8
; CHECK-NEXT:    [[TMP11:%.*]] = call ptr @__instrumentor_pre_globals(ptr @B4, ptr @__instrumentor_.str.11, i64 0, i32 8, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP11]], ptr @__instrumentor_shadow.B4, align 8
; CHECK-NEXT:    [[TMP12:%.*]] = call ptr @__instrumentor_pre_globals(ptr @B5, ptr @__instrumentor_.str.12, i64 0, i32 0, i8 0) #[[ATTR0]]
; CHECK-NEXT:    [[TMP13:%.*]] = call ptr @__instrumentor_pre_globals(ptr @B6, ptr @__instrumentor_.str.13, i64 0, i32 0, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store [100 x i32] zeroinitializer, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP14:%.*]] = call ptr @__instrumentor_pre_globals_ind(ptr @C1, ptr @__instrumentor_.str.14, ptr [[TMP1]], i32 400, i8 0) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP14]], ptr @__instrumentor_shadow.C1, align 8
; CHECK-NEXT:    store [100 x i32] zeroinitializer, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP15:%.*]] = call ptr @__instrumentor_pre_globals_ind(ptr @C2, ptr @__instrumentor_.str.15, ptr [[TMP1]], i32 400, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP15]], ptr @__instrumentor_shadow.C2, align 8
; CHECK-NEXT:    store [100 x i32] zeroinitializer, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP16:%.*]] = call ptr @__instrumentor_pre_globals_ind(ptr @C3, ptr @__instrumentor_.str.16, ptr [[TMP1]], i32 400, i8 0) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP16]], ptr @__instrumentor_shadow.C3, align 8
; CHECK-NEXT:    store [100 x i32] zeroinitializer, ptr [[TMP1]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = call ptr @__instrumentor_pre_globals_ind(ptr @C4, ptr @__instrumentor_.str.17, ptr [[TMP1]], i32 400, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP17]], ptr @__instrumentor_shadow.C4, align 8
; CHECK-NEXT:    [[TMP18:%.*]] = call ptr @__instrumentor_pre_globals(ptr @C5, ptr @__instrumentor_.str.18, i64 0, i32 0, i8 0) #[[ATTR0]]
; CHECK-NEXT:    [[TMP19:%.*]] = call ptr @__instrumentor_pre_globals(ptr @C6, ptr @__instrumentor_.str.19, i64 0, i32 0, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store x86_fp80 0xK00000000000000000000, ptr [[TMP0]], align 16
; CHECK-NEXT:    [[TMP20:%.*]] = call ptr @__instrumentor_pre_globals_ind(ptr @D1, ptr @__instrumentor_.str.20, ptr [[TMP0]], i32 16, i8 0) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP20]], ptr @__instrumentor_shadow.D1, align 8
; CHECK-NEXT:    store x86_fp80 0xK00000000000000000000, ptr [[TMP0]], align 16
; CHECK-NEXT:    [[TMP21:%.*]] = call ptr @__instrumentor_pre_globals_ind(ptr @D2, ptr @__instrumentor_.str.21, ptr [[TMP0]], i32 16, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP21]], ptr @__instrumentor_shadow.D2, align 8
; CHECK-NEXT:    store x86_fp80 0xK00000000000000000000, ptr [[TMP0]], align 16
; CHECK-NEXT:    [[TMP22:%.*]] = call ptr @__instrumentor_pre_globals_ind(ptr @D3, ptr @__instrumentor_.str.22, ptr [[TMP0]], i32 16, i8 0) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP22]], ptr @__instrumentor_shadow.D3, align 8
; CHECK-NEXT:    store x86_fp80 0xK00000000000000000000, ptr [[TMP0]], align 16
; CHECK-NEXT:    [[TMP23:%.*]] = call ptr @__instrumentor_pre_globals_ind(ptr @D4, ptr @__instrumentor_.str.23, ptr [[TMP0]], i32 16, i8 1) #[[ATTR0]]
; CHECK-NEXT:    store ptr [[TMP23]], ptr @__instrumentor_shadow.D4, align 8
; CHECK-NEXT:    [[TMP24:%.*]] = call ptr @__instrumentor_pre_globals(ptr @D5, ptr @__instrumentor_.str.24, i64 0, i32 0, i8 0) #[[ATTR0]]
; CHECK-NEXT:    [[TMP25:%.*]] = call ptr @__instrumentor_pre_globals(ptr @D6, ptr @__instrumentor_.str.25, i64 0, i32 0, i8 0) #[[ATTR0]]
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define private void @__instrumentor_dtor() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @__instrumentor_post_module(ptr @__instrumentor_.str, ptr @__instrumentor_.str.1) #[[ATTR0]]
; CHECK-NEXT:    ret void
;
